os: linux

dist: xenial

sudo: false

# Enable C++ support
language: cpp

compiler:
  - gcc
  - clang

# Build steps
script:
  - cmake -DCMAKE_CXX_COMPILER=$CXX_FOR_BUILD -DCMAKE_BUILD_TYPE=Release -S . -B build
  - cmake --build build --clean-first --verbose
  - cmake -E chdir build ctest --verbose
