os: linux

dist: xenial

sudo: false

# Enable C++ support
language: cpp

compiler:
  - gcc
  - clang

# Build steps
script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX_FOR_BUILD -DCMAKE_BUILD_TYPE=Release ..
  - VERBOSE=1 make
  - ctest --verbose
